_core:
  default_config_hash: VDJxTZtQR21qB4lvOq8zszJZLvLKrSPQpdn2E3T71Ww
langcode: en
uuid: 3e049925-e04f-4c51-8c3f-5db516fe8ca0
name: 'Drupaljam 2022 DDev Demo'
mail: e.escribano@youweagency.com
slogan: ''
page:
  403: ''
  404: ''
  front: /node
admin_compact_mode: false
weight_select_max: 100
default_langcode: en
