version: '3.6'
services:
  solr:
    container_name: ddev-${DDEV_SITENAME}-solr
    image: solr:8
    restart: "no"
    ports:
      - 8983
    labels:
      com.ddev.site-name: ${DDEV_SITENAME}
      com.ddev.approot: $DDEV_APPROOT
    environment:
      - VIRTUAL_HOST=$DDEV_HOSTNAME
      - HTTP_EXPOSE=8983:8983
    volumes:
      - solr:/opt/solr
      - .:/mnt/ddev_config
      - ./solr-demo:/solr-demo-conf
      - ./solr-umami:/solr-umami-conf
      - "./solr/solr-configupdate.sh:/docker-entrypoint-initdb.d/solr-configupdate.sh"
    entrypoint: [ "sh", "-c", "docker-entrypoint.sh precreate-core demo /solr-demo-conf; docker-entrypoint.sh precreate-core umami /solr-umami-conf; exec solr -f" ]
    external_links:
      - "ddev-router:${DDEV_SITENAME}.${DDEV_TLD}"
  web:
    links:
      - solr:solr

volumes:
  solr:
